POST http://localhost:3000/games
Content-Type: application/json

{
  "title": "Valorant",
  "description": "Jogo de FPS",
  "imgUrl": "link",
  "qtdPlayers": "32.000",
  "price": "Gratuito"
}

###
GET http://localhost:3000/games?search=Valorant


